### ISSUE TITLE
When not in a git repository, git_dashboard[#git_dashboard] returns a non-empty value

### ISSUE THREAD

**Issue by msdone-lwt** [juansalvatore/git-dashboard-nvim#11]
e44e44e2dc9c85a90ff3756eb216cf346dc9306d The version is fine, the latest commit 90d262c2a91176e834827eed3531c981085fb5d3 has this issue
![image](https://github.com/user-attachments/assets/277e3126-8d40-4910-b619-37d484fd566f)
The above code, when in e44e44e2dc9c85a90ff3756eb216cf346dc9306d, vim will notify "nil" message, but in version 90d262c2a91176e834827eed3531c981085fb5d3, vim notifies non-nil value：
![image](https://github.com/user-attachments/assets/b0ee6fd6-c43c-4cc2-87aa-849313a23774)
This leads to a problem: when I'm not in the Git repository directory:
e44e44e2dc9c85a90ff3756eb216cf346dc9306d:
![image](https://github.com/user-attachments/assets/a2ab73e3-89a9-4ae3-9a00-c690eec550b4)
90d262c2a91176e834827eed3531c981085fb5d3:
![image](https://github.com/user-attachments/assets/30a22f66-b966-4ea2-856b-ba8b80d1d982)
I usually work in a Git repository：  
![image](https://github.com/user-attachments/assets/1a36febb-ac39-40b1-aeba-df367d1e56e3)

**Comment by csessh** [comment]
I can probably do an initial explicit check for non git repo to return empty string value

**Comment by csessh** [comment]
@msdone-lwt you mind testing #12 against your case?

**Comment by msdone-lwt** [comment]
https://github.com/juansalvatore/git-dashboard-nvim/pull/12 Does not work，
![image](https://github.com/user-attachments/assets/49534d7e-3fec-4b0d-956e-2427b8d8faaf)
![image](https://github.com/user-attachments/assets/9ecf1810-5ed8-4c5a-a5a0-8ed6746bec95)

**Comment by csessh** [comment]
you mind sharing your plugin config? @msdone-lwt

**Comment by msdone-lwt** [comment]
当然，[#12 ](https://github.com/juansalvatore/git-dashboard-nvim/pull/12) 甚至在一个 git 目录下返回 nil。
https://github.com/msdone-lwt/AstroNvimConfig/blob/main/lua/plugins/user.lua#L280

**Comment by msdone-lwt** [comment]
Of course, https://github.com/msdone-lwt/AstroNvimConfig/blob/main/lua/plugins/user.lua#L280.
https://github.com/juansalvatore/git-dashboard-nvim/pull/12 even returns nil in a git directory.

**Comment by csessh** [comment]
umm this config still uses the latest version from GitHub, not the staging version in #12 
https://github.com/msdone-lwt/AstroNvimConfig/blob/main/lua/plugins/git-dashboard-nvim.lua

clone my fork and try again. hopefully we get a different result:
```bash
git clone git@github.com:csessh/git-dashboard-nvim.git
git checkout bug-non-git-repo
```

try this in https://github.com/msdone-lwt/AstroNvimConfig/blob/main/lua/plugins/git-dashboard-nvim.lua

```
return {
  {
    -- "juansalvatore/git-dashboard-nvim",
    dev = true,
    dir = /path/to/where/you/clone/my/fork
    event = "VeryLazy",
    config = function()
      require("git-dashboard-nvim").setup {
        -- filled_squares = { "", "", "", "", "", "" },
        empty_square = "0",
        filled_squares = { "1", "2", "3", "4", "5", "6" },
      }
    end,
  },
}
```

**Comment by msdone-lwt** [comment]
![image](https://github.com/user-attachments/assets/2221de79-43cf-4b11-96dc-2c06d6d5db25)

**Comment by msdone-lwt** [comment]
I'm sure, I pulled your code because the behavior of git-dashboard changed after I switched branches. I directly modified the code under ~/.local/share/nvim.

**Comment by csessh** [comment]
ah cool. thanks. I'll take a looksie 👍🏾

**Comment by msdone-lwt** [comment]
Thank you, please
