### ISSUE TITLE
NUL file created when opening nvim

### ISSUE THREAD

**Issue by sudo-tee** [juansalvatore/git-dashboard-nvim#7]
I have an issue where everytime I open nvim a `NUL` file is created on linux

I investigated and found that the issue was with the way windows detection is done in the file git.lua

```lua
local is_windows = vim.fn.has("win32")
```
is_windows will be `0` at that point and 

```lua
local null = is_windows and "NUL" or "/dev/null"
```
Since lua does not interpret `0` as being false the null file is then 'NUL'

the windows check sould be

```lua
local is_windows = vim.fn.has("win32") == 1
```

Thanks for your great plugin

**Comment by juansalvatore** [comment]
Thanks for checking this and sharing the corrected check!
